modLoader="javafml"
loaderVersion="${fml_range}"
license="GPL3"

[[mods]]
modId="blockui"
version="${version}"
displayName="UI Library Mod"
credits="LDT Team"
authors="LDT Team"
description='''
UI Library mod, use ctrl+alt+shift+x to open a test-ui
'''

[[dependencies.blockui]]
    modId="neoforge"
    type="required"
    versionRange="${forge_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.blockui]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_range}"
    ordering="NONE"
    side="BOTH"
